// AUTO-GENERATED from partybox-rn 5secondquestions.ts — Polish only.
// Do not edit by hand; regenerate if the source question bank changes.

export const CATEGORY_LABELS = {
  "animals": "Zwierzęta i przyroda",
  "food": "Jedzenie i picie",
  "geo": "Geografia",
  "sport": "Sport",
  "movies": "Filmy i seriale",
  "music": "Muzyka",
  "brands": "Marki i technologia",
  "history": "Historia i kultura",
  "misc": "Różności"
};

export const DIFFICULTY_LABELS = {
  "easy": "Łatwy",
  "medium": "Średni",
  "hard": "Trudny"
};

export const QUESTIONS = [
  { q: "Podaj 3 rasy psów", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 rasy kotów", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 gatunki ptaków", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 gatunki drzew", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 drzewa owocowe", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 owoce egzotyczne", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 kwiaty", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 kwiaty polne", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 warzywa liściaste", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 zwierzęta morskie", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 zwierzęta sawanny", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 jadowite zwierzęta", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 rasy koni", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 kolory tęczy", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 zwierzęta domowe", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 zwierzęta żyjące na wsi (w gospodarstwie)", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 zwierzęta żyjące w lesie", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 gatunki ssaków", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 gatunki gadów", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 drapieżniki lądowe", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 owady latające", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 ptaki śpiewające", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 gatunki gryzoni", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 drzewa iglaste", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 drzewa liściaste", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 owoce cytrusowe", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 popularne kwiaty doniczkowe", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 zwierzęta, które mają rogi", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 zwierzęta zapadające w sen zimowy", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 ptaki zimujące w Polsce", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 gatunki ryb akwariowych", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 zwierzęta, które wykluwają się z jaj", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 zwierzęta o czarno-białym ubarwieniu", cat: "animals", difficulty: "easy" },
  { q: "Podaj 3 gatunki rekinów", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki niedźwiedzi", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 owady pożyteczne", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki papug", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki pingwinów", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 zwierzęta Australii", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 zwierzęta Arktyki", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 najszybsze zwierzęta na świecie", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki węży", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 nocne zwierzęta", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki żab", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki małp", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki ryb", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 ptaki nielatające", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 grzyby jadalne", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 grzyby trujące", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 rośliny lecznicze", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 dinozaury", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 ssaki morskie", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki dzikich kotów", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki wielorybów", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 ptaki wodne", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 ptaki wędrowne", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki sów", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki płazów", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 zwierzęta z pancerzem lub skorupą", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki żółwi", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 zwierzęta pustynne", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 zwierzęta żyjące w tundrze", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 zwierzęta żyjące w dżungli amazońskiej", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 zwierzęta pochodzące z Madagaskaru", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki antylop", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 rasy krów", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 gatunki mrówek", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 owady będące szkodnikami roślin", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 rośliny owadożerne", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 popularne krzewy owocowe", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 chwasty polne", cat: "animals", difficulty: "medium" },
  { q: "Podaj 3 zwierzęta zagrożone wyginięciem", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 gatunki delfinów", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 gatunki motyli", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 gatunki orłów", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 gatunki małp człekokształtnych", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 gatunki dzikich psowatych", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 gatunki jadowitych pająków", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 gatunki nietoperzy", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 gatunki jaszczurek", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 gatunki chrząszczy", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 owady pasożytnicze", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 torbacze", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 drapieżne torbacze", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 zwierzęta głębinowe", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 bezkręgowce morskie", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 endemity z wysp Galapagos", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 wymarłe gatunki zwierząt (inne niż dinozaury)", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 ptaki, które potrafią naśladować ludzką mowę", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 rasy koni zimnokrwistych", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 rasy owiec", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 rośliny trujące rosnące w Polsce", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 gatunki storczyków", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 drzewa rosnące w strefie równikowej", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 gatunki koralowców rafotwórczych", cat: "animals", difficulty: "hard" },
  { q: "Podaj 3 polskie zupy", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 rodzaje makaronu", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 rodzaje pieczywa", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 warzywa korzeniowe", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 polskie słodycze", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 rodzaje deserów", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 smaki lodów", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 rodzaje czekolady", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 owoce jagodowe", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 napoje bezalkoholowe", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 dania kuchni włoskiej", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 rodzaje pizzy", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 składniki pizzy Margherita", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 rodzaje herbaty", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 rodzaje sera", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 rodzaje Coli", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 owoce, które trzeba obierać ze skóry", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 warzywa, które można jeść na surowo", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 potrawy z jajek", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 popularne fast foody", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 rzeczy, które można zjeść na śniadanie", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 dodatki do kanapek", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 rodzaje mięsa", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 popularne sosy do potraw", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 dania z ziemniaków", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 chrupiące przekąski", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 wypieki z piekarni", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 potrawy, które jemy łyżką", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 owoce o czerwonym kolorze", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 popularne smaki soków owocowych", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 owoce, które mają w środku dużą pestkę", cat: "food", difficulty: "easy" },
  { q: "Podaj 3 rodzaje kawy", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 rodzaje sushi", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 marki piwa", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 przyprawy kuchenne", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 dania kuchni meksykańskiej", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 potrawy kuchni greckiej", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 potrawy kuchni chińskiej", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 rodzaje tortów", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 potrawy z grilla", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 zupy na zimę", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 rodzaje wina", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 potrawy kuchni japońskiej", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 rodzaje sałatek", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 rodzaje dżemu", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 polskie dania wigilijne", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 gatunki ryb jadalnych", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 odmiany jabłek", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 dania kuchni amerykańskiej", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 potrawy kuchni hiszpańskiej", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 tradycyjne polskie dania wielkanocne", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 gatunki orzechów", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 rodzaje mąki", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 rodzaje oleju jadalnego", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 rodzaje kaszy", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 warzywa strączkowe", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 grzyby powszechnie dodawane do potraw", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 rodzaje musztardy", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 słodkie wypieki z jabłkami", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 sery dojrzewające", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 popularne koktajle alkoholowe", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 dania, w których głównym składnikiem jest ryż", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 rodzaje octu", cat: "food", difficulty: "medium" },
  { q: "Podaj 3 rodzaje serów pleśniowych", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 potrawy kuchni indyjskiej", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 potrawy kuchni tureckiej", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 potrawy kuchni tajskiej", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 potrawy kuchni francuskiej", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 potrawy kuchni arabskiej", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 włoskie desery", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 rodzaje owoców morza", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 przyprawy korzenne", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 odmiany papryczek chili", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 gatunki białego wina", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 gatunki czerwonego wina", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 jadalne kwiaty", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 składniki tradycyjnego śniadania angielskiego", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 rodzaje wegańskich zamienników mleka", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 potrawy z surowego mięsa lub ryby", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 części wołowiny (np. antrykot)", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 słynne francuskie sery", cat: "food", difficulty: "hard" },
  { q: "Podaj 3 polskie miasta", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 polskie miejscowości nad morzem", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 rzeki w Polsce", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 góry w Polsce", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 polskie jeziora", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 miasta Niemiec", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 miasta Francji", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 miasta Hiszpanii", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 miasta Włoch", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 państwa w Europie", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 stolice europejskie", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 kraje Azji", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 kraje Afryki", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 stany USA", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 kontynenty", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 oceany", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 państwa sąsiadujące z Polską", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 województwa w Polsce", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 polskie miasta na literę W", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 miasta w Wielkiej Brytanii", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 stolice państw sąsiadujących z Polską", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 główne kierunki geograficzne", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 państwa leżące nad Morzem Śródziemnym", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 państwa w Ameryce Północnej", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 dzielnice Warszawy", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 długie rzeki na świecie", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 kraje z trójkolorową flagą", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 polskie krainy geograficzne (np. Śląsk)", cat: "geo", difficulty: "easy" },
  { q: "Podaj 3 polskie parki narodowe", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 państwa wyspiarskie w Europie", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje z symbolem gwiazdy na fladze", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 miasta sąsiadujące z Warszawą", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 państwa, przez które przebiega równik", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 polskie porty morskie", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 znane polskie szczyty górskie", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 polskie jeziora mazurskie", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje z czerwono-białą flagą", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 polskie zamki", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 polskie miasta nad Wisłą", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 polskie pasma górskie", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 polskie rzeki dopływy Wisły", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 polskie miasta na literę K", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 stolice Azji", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje Skandynawii", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje Bałkanów", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje Bliskiego Wschodu", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje Ameryki Środkowej", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje Ameryki Południowej", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje Europy Środkowej", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 rzeki w Europie", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 rzeki Azji", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 góry w Alpach", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 jeziora Afryki", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 pustynie świata", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje z pustynią", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje wyspiarskie", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 wyspy Karaibów", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 rodzaje klimatu", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 państwa byłego ZSRR", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje bez dostępu do morza", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje bez strefy euro leżące w Europie", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 planety Układu Słonecznego", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 amerykańskie miasta na zachodnim wybrzeżu", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 państwa leżące nad Morzem Bałtyckim", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 polskie puszcze lub lasy", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 afrykańskie rzeki", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 słynne wulkany na świecie", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje Półwyspu Iberyjskiego", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 polskie parki krajobrazowe", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 morza oblewające Europę", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 państwa z symbolem krzyża na fladze", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 miasta w Australii", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 włoskie regiony (np. Toskania)", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 państwa leżące w Andach", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 mniejszości narodowe lub etniczne żyjące w Polsce", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 znane kanały wodne na świecie", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 angielskojęzyczne kraje w Afryce", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 europejskie mikropaństwa", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje w Europie niebędące członkami Unii Europejskiej ani strefy Schengen", cat: "geo", difficulty: "medium" },
  { q: "Podaj 3 kraje z monarchią", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 wyspy należące do Hiszpanii", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 stany w USA na literę C", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 państwa, przez które przepływa Dunaj", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 stany wschodniego wybrzeża USA", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 polskie jaskinie", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 kraje Afryki Zachodniej", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 wyspy Pacyfiku", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 wyspy Morza Śródziemnego", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 planety karłowate", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 terytoria zależne Wielkiej Brytanii", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 państwa śródlądowe w Azji", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 afrykańskie kraje leżące na równiku", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 stolice państw leżące na półkuli południowej", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 morza oblewające wybrzeża Antarktydy", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 państwa, w których obowiązuje ruch lewostronny (poza Wielką Brytanią)", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 kraje, przez które przepływa Amazonka", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 amerykańskie stany nieposiadające dostępu do oceanu", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 najmniejsze państwa świata pod względem powierzchni", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 półwyspy w Europie", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 rzeki wpadające do Morza Bałtyckiego", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 państwa w Ameryce Południowej, w których nie mówi się po hiszpańsku", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 państwa położone na Półwyspie Indochińskim", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 wulkany znajdujące się w Europie", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 azjatyckie tygrysy gospodarcze", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 oceany oblewające Amerykę Północną", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 kraje, które posiadają terytoria na więcej niż jednym kontynencie", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 rzeki będące dopływami Odry", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 państwa, które graniczą z tylko jednym krajem", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 stolice państw leżące na wysokości powyżej 2000 m n.p.m.", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 największe wyspy na świecie (nie licząc kontynentów)", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 cieśniny łączące morza lub oceany", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 amerykańskie stany graniczące z Meksykiem", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 najwyższe szczyty kontynentów (należące do Korony Ziemi)", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 prowincje lub terytoria Kanady", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 państwa leżące wokół Morza Kaspijskiego", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 państwa położone w Rogu Afryki", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 morza wewnętrzne", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 państwa, w których język portugalski jest językiem urzędowym (poza Portugalią)", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 stolice państw afrykańskich", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 kraje, z którymi Polska graniczyła przed II wojną światową", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 archipelagi na Oceanie Indyjskim", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 kraje z flagą w barwach wyłącznie żółtej, niebieskiej i czerwonej", cat: "geo", difficulty: "hard" },
  { q: "Podaj 3 sporty drużynowe", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 sporty zimowe", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 sporty wodne", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 dyscypliny olimpijskie", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 dyscypliny zimowych igrzysk", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 polskie kluby piłkarskie", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 polskich piłkarzy", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 słynnych piłkarzy świata", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 skoczków narciarskich", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 pozycje na boisku piłkarskim", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 dyscypliny sportowe, w których używa się rakiety", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 dyscypliny sportowe, w których używa się piłki", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 sporty, w których można zdobyć gola", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 style pływackie", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 sporty ekstremalne", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 znane stadiony piłkarskie na świecie", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 polskie reprezentacje narodowe", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 elementy stroju piłkarza", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 kolory medali olimpijskich", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 sporty motorowe", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 sporty, które uprawia się na lodzie", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 sporty, które uprawia się na śniegu", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 sporty, w które gra się na plaży", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 dyscypliny gimnastyczne", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 sporty, w których zawodnicy noszą kaski", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 gry sportowe, w których używa się siatki", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 przyrządy do ćwiczeń na siłowni", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 znane marki sprzętu sportowego", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 kraje słynące z dobrej piłki nożnej", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 wschodnie sztuki walki", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 dyscypliny jeździeckie", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 polskie stadiony sportowe", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 sporty, w których nie używa się piłki", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 sporty, w których wykorzystuje się deskę", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 historyczne sukcesy polskiej reprezentacji w piłce nożnej", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 podstawowe części roweru", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 popularne ćwiczenia fitness", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 dyscypliny oparte na celności (np. rzutki, łucznictwo)", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 przedmioty używane przez sędziego w piłce nożnej", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 dystanse biegowe w lekkoatletyce", cat: "sport", difficulty: "easy" },
  { q: "Podaj 3 angielskie kluby piłkarskie", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 niemieckie kluby piłkarskie", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 kluby piłkarskie z Hiszpanii", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 kluby piłkarskie z Włoch", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 drużyny NBA", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 zespoły Formuły 1", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 wyścigi Formuły 1", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 słynnych skoczków narciarskich", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 słynnych tenisistów", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 słynnych koszykarzy", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 słynnych pływaków", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 słynnych kolarzy", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 słynnych bokserów", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 zawodników MMA", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 sporty walki", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 dyscypliny lekkoatletyczne", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 polskich siatkarzy", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 polskich sportowców olimpijskich", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 rodzaje ćwiczeń fizycznych", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 francuskie kluby piłkarskie", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 słynnych kierowców Formuły 1", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 znane tenisistki", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 pozycje zawodników w koszykówce", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 pozycje zawodników w siatkówce", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 polskich skoczków narciarskich", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 reprezentacje narodowe, które wygrały piłkarski Mundial", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 dyscypliny kolarskie", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 wielkie wyścigi kolarskie (tzw. Grand Toury)", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 słynnych trenerów piłkarskich", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 sporty rozgrywane na kortach lub boiskach trawiastych", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 konkurencje rzutowe w lekkoatletyce", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 polskie kluby siatkarskie", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 drużyny ligi hokejowej NHL", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 znanych komentatorów sportowych w Polsce", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 konkurencje wchodzące w skład triathlonu", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 rodzaje trofeów lub medali przyznawanych w sporcie", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 europejskie puchary w piłce nożnej (np. Liga Mistrzów)", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 ciosy lub kopnięcia z różnych sportów walki", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 reguły lub kary w piłce nożnej (np. spalony)", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 znane turnieje tenisowe (poza Wielkimi Szlemami)", cat: "sport", difficulty: "medium" },
  { q: "Podaj 3 turnieje Grand Slam w tenisie", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 drużyny NFL", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 polskie medalistki olimpijskie", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 zawody gimnastyczne", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 drużyny baseballowe z ligi MLB", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 piłkarzy, którzy zdobyli nagrodę Złotej Piłki", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 miasta gospodarzy Letnich Igrzysk Olimpijskich", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 miasta gospodarzy Zimowych Igrzysk Olimpijskich", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 dyscypliny sportowe, w których bierze udział koń", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 oficjalne warianty gry w bilard lub snookera", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 żeglarskie klasy olimpijskie", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 polskie mistrzynie świata w lekkoatletyce", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 kluby piłkarskie, które wygrały Ligę Mistrzów więcej niż 3 razy", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 sztuki walki, które znalazły się w programie Igrzysk Olimpijskich", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 dyscypliny sportowe, w których występuje system wyzwań wideo (VAR, Challenge)", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 aktualnych lub historycznych rekordzistów świata w lekkoatletyce", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 polskich kierowców wyścigowych lub rajdowych", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 słynne turnieje lub cykle zawodów żużlowych", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 utytułowanych polskich żużlowców", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 nietypowe zagrania lub otwarcia w szachach", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 dyscypliny, które kiedyś były na Igrzyskach, ale zostały z nich usunięte", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 rekordzistów w biegu maratońskim", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 znane polskie zawodniczki MMA", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 turnieje tenisowe rangi ATP Masters 1000", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 style w karate", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 polskie stadiony lekkoatletyczne spełniające wymogi mistrzostw", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 drużyny narodowe biorące udział w Pucharze Sześciu Narodów (rugby)", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 pozycje zawodników w futbolu amerykańskim", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 polskie wioślarki z medalami olimpijskimi", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 główne konkurencje w łyżwiarstwie figurowym", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 style pływackie używane na dystansie 400 metrów stylem zmiennym", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 polskie męskie kluby koszykarskie z największymi tradycjami", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 specjalistyczne określenia uderzeń w tenisie ziemnym (np. forehand)", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 najważniejsze turnieje golfowe (tzw. majory)", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 historycznych mistrzów świata w boksie w wadze ciężkiej", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 państwa, które kiedykolwiek wygrały Mistrzostwa Europy (EURO) w piłce nożnej", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 najsłynniejsze hale sportowe w USA (np. Madison Square Garden)", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 polskich medalistów olimpijskich w podnoszeniu ciężarów", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 znanych zawodników z Pucharu Świata w narciarstwie alpejskim", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 państwa, które dominują w klasyfikacji medalowej wszech czasów letnich igrzysk olimpijskich", cat: "sport", difficulty: "hard" },
  { q: "Podaj 3 filmy Disneya", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy animowane inne niż Disney", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 polskie filmy animowane", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy Marvela", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy z dinozaurami", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 znane bajki dla dzieci", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 seriale dla dzieci", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 polskie seriale", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 polskie komedie filmowe", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 seriale Netfliksa", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 polskich aktorów", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 polskie aktorki", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy ze światem Minionków", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 popularne postacie z filmów Disneya", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 znane komedie romantyczne", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 kultowe filmy świąteczne", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy, w których głównymi bohaterami są zwierzęta", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 polskie seriale komediowe", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 klasyczne bajki z Cartoon Network", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy, których akcja dzieje się w kosmosie", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy o magii lub czarodziejach", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 postacie z sagi Gwiezdne Wojny", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 bajki wyprodukowane przez studio DreamWorks", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 popularne filmy akcji", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy, w których występują kosmici", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 słynnych hollywoodzkich aktorów", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 słynne hollywoodzkie aktorki", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 programy rozrywkowe w polskiej telewizji", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 polskie stacje telewizyjne", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 serie filmowe, które mają więcej niż 3 części", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy, w których głównym bohaterem jest pies", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 znane polskie dobranocki z dawnych lat", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmowych superbohaterów (ogólnie)", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 słynne czarne charaktery z bajek", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy zrealizowane na podstawie komiksów", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy o tematyce sportowej", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 znane musicale filmowe", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 filmy o agentach i szpiegach", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 nagrody przyznawane w świecie filmu i telewizji (np. Oscary)", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 polskie filmy historyczne", cat: "movies", difficulty: "easy" },
  { q: "Podaj 3 seriale kryminalne", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy science fiction", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy o wampirach", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy o robotach", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy o piratach", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 horrory filmowe", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy o superbohaterach DC", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 superbohaterów Marvela", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy z Tomem Hanksem", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy z Arnoldem Schwarzeneggerem", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy ze Sylvestrem Stallone", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy z Keanu Reevesem", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy z Leonardo DiCaprio", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy o przygodach Jamesa Bonda", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy w reżyserii Stevena Spielberga", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy w reżyserii Quentina Tarantino", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 polskich reżyserów filmowych", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy w reżyserii Tima Burtona", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy z Angeliną Jolie", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy z Bradem Pittem", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 polskie filmy sensacyjne lub kryminalne", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 tytuły z serii filmów o Harrym Potterze", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 epizody (podtytuły) Gwiezdnych Wojen", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 seriale z gatunku fantasy", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy lub seriale o zombie", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 aktorów wcielających się w rolę Jamesa Bonda", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy z Johnnym Deppem", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 seriale medyczne", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 kultowe filmy z lat 80.", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 popularne polskie seriale z lat 90. lub 00.", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 głównych bohaterów z serialu Przyjaciele", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy z motywem podróży w czasie", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 klasyczne westerny", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 filmy animowane studia Pixar", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 seriale animowane dla dorosłych", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 polskie filmy nagrodzone lub nominowane do Oscara", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 adaptacje filmowe książek Stephena Kinga", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 znanych aktorów grających w uniwersum Marvela (MCU)", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 polskie ekranizacje lektur szkolnych", cat: "movies", difficulty: "medium" },
  { q: "Podaj 3 seriale koreańskie", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 oryginalne seriale HBO", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy w reżyserii Christophera Nolana", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 głośne filmy z lat 90.", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy wyreżyserowane przez Martina Scorsese", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy w reżyserii Alfreda Hitchcocka", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 produkcje, które zdobyły Oscara za najlepszy film", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 polskie filmy zaliczane do nurtu Polskiej Szkoły Filmowej", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 znanych reżyserów kina europejskiego (spoza Polski)", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy anime w reżyserii Hayao Miyazakiego (Studio Ghibli)", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 seriale oryginalne platformy Amazon Prime Video", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 seriale oryginalne Apple TV+", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 głośne brytyjskie seriale", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy, w których główną rolę zagrał Robert De Niro", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy z udziałem Meryl Streep", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 hiszpańskojęzyczne seriale", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 znane francuskie komedie filmowe", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 polskie filmy lub aktorów z okresu dwudziestolecia międzywojennego", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 aktorów kojarzonych z epoką kina niemego", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy w reżyserii Stanleya Kubricka", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 kultowe filmy science fiction z lat 70. lub 80.", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 najważniejsze festiwale filmowe na świecie (np. w Cannes)", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 nagrody przyznawane na europejskich festiwalach filmowych (np. Złota Palma)", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 wybitnych polskich kompozytorów muzyki filmowej", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy z muzyką skomponowaną przez Hansa Zimmera", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 aktorów, którzy otrzymali Oscara pośmiertnie lub odmówili jego przyjęcia", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 produkcje (filmy lub seriale) w reżyserii Davida Lyncha", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 aktorki, które zdobyły Oscara w kategorii Najlepsza Aktorka Pierwszoplanowa", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy nakręcone na podstawie komiksów innych niż te od Marvela i DC", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 czarno-białe filmy uznawane za arcydzieła światowego kina", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 seriale opowiadające o brytyjskiej rodzinie królewskiej lub arystokracji", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 polskie seriale kryminalne klasy premium (np. produkcji Canal+, HBO, Belfer)", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 amerykańskie sitcomy z lat 80. lub starsze", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy w reżyserii Romana Polańskiego", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 znane produkcje zaliczane do kina skandynawskiego", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy wyreżyserowane przez Davida Finchera", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 filmy, które zapoczątkowały znane uniwersa grozy (np. Obecność, Piła)", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 nagradzanych na świecie polskich operatorów filmowych", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 seriale osadzone w klimatach dystopii lub cyberpunku", cat: "movies", difficulty: "hard" },
  { q: "Podaj 3 słynne piosenkarki pop", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 polskich piosenkarzy", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 polskich raperów", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 gatunki muzyczne", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 instrumenty muzyczne", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 zagranicznych raperów", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 słynnych piosenkarzy pop (mężczyzn)", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 polskie piosenkarki pop", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 amerykańskie gwiazdy R&B lub pop", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 piosenki Michaela Jacksona", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 piosenki Madonny", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 polskie hity hip-hopowe", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 gwiazdy k-popu (zespoły lub soliści)", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 instrumenty klawiszowe", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 aplikacje lub serwisy do słuchania muzyki", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 piosenki Dawida Podsiadło", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 piosenki Sanah", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 programy telewizyjne typu talent show dla piosenkarzy", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 piosenki Eminema", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 znane piosenki świąteczne", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 brytyjskich piosenkarzy pop", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 latynoskich wykonawców pop", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 piosenki z filmów Disneya", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 znane boysbandy", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 znane girlsbandy", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 instrumenty wchodzące w skład orkiestry symfonicznej", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 stacje telewizyjne emitujące głównie teledyski muzyczne", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 zagraniczne wokalistki, które zaczynały karierę w Disneyu", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 polskich artystów rap/trap z młodego pokolenia", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 artystów, którzy wystąpili na Super Bowl Halftime Show", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 polskie wytwórnie hip-hopowe", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 akcesoria potrzebne gitarzyście (np. kostka)", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 piosenki popularne jako trendy na TikToku", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 przedmioty służące do odtwarzania muzyki", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 piosenki Justina Biebera", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 gatunki tańca nowoczesnego (często widziane w teledyskach)", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 artystów, z którymi Snoop Dogg nagrał wspólną piosenkę", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 polskie utwory, które są popularne na weselach", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 polskie utwory hip-hopowe", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 piosenki Rihanny", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 piosenki Kendricka Lamara", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 piosenki Kanye Westa", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 hity 50 Centa", cat: "music", difficulty: "easy" },
  { q: "Wymień 3 zagranicznych artystów, którzy występowali na polskich festiwalach", cat: "music", difficulty: "easy" },
  { q: "Podaj 3 polskie zespoły rockowe", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 albumy Eminema", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 piosenki Beatlesów", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 polskich reprezentantów na Eurowizji", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 zagraniczne zespoły rockowe", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 zespoły muzyczne z lat 80.", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 polskie zespoły hip-hopowe", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 słynnych wokalistów rockowych", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 piosenkarzy reggae", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 słynnych gitarzystów", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 słynnych DJ-ów (np. tworzących muzykę EDM, house)", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 instrumenty perkusyjne", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 instrumenty strunowe", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 instrumenty dęte", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 wielkie zagraniczne festiwale muzyczne", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 polskie festiwale muzyczne", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 nagrody muzyczne", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 amerykańskich raperów z lat 90. (tzw. złota era hip-hopu)", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 raperów z zachodniego wybrzeża USA (West Coast)", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 raperów ze wschodniego wybrzeża USA (East Coast)", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 polskie albumy hip-hopowe, które przeszły do historii", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 słynnych producentów muzyki hip-hopowej", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 wokalistki o bardzo mocnym i uznanym głosie (np. Whitney Houston)", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 piosenki Beyoncé", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 piosenki zespołu Queen", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 głośne muzyczne duety w muzyce pop lub hip-hop", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 polskie wokalistki rockowe lub alternatywne", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 podgatunki muzyki elektronicznej (np. techno, dubstep)", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 polskie piosenki z lat 80. lub 90.", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 zespoły grające heavy metal", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 wykonawców muzyki country", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 artystów tworzących muzykę disco polo", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 hity polskiego hip-hopu lat 2000.", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 piosenki Taco Hemingwaya", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 artystów popowych, którzy zagrali główne role w filmach", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 piosenki, w których występuje słynne solo gitarowe", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 polskie stacje radiowe grające muzykę pop", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 zagranicznych wokalistów pop z lat 2000. i 2010.", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 żeńskie raperki z USA", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 piosenki Ariany Grande", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 polskie piosenki, w których raper dograł zwrotkę (tzw. featuring)", cat: "music", difficulty: "medium" },
  { q: "Podaj 3 słynnych pianistów", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 słynnych pianistów jazzowych", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 wokalistów jazzowych", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 słynnych skrzypków", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 tytuły oper", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 kompozytorów muzyki klasycznej", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 polskie śpiewaczki operowe", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 słynnych kompozytorów muzyki filmowej", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 słynnych dyrygentów", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 podgatunki hip-hopu (np. boom bap, trap)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 członków legendarnej rapowej grupy Wu-Tang Clan", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 polskie podziemne składy hip-hopowe (lub ekipy z wczesnych lat 90.)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 amerykańskich raperów, którzy zdobyli status diamentowej płyty (sprzedali ponad 10 mln kopii albumu/singla)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 twórców tzw. mumble rapu lub chmurnego rapu (cloud rap)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 brytyjskich raperów (scena grime / UK drill)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 artystów reprezentujących francuski hip-hop", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 utwory (lub formy muzyczne, np. nokturn) Fryderyka Chopina", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 znane balety klasyczne", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 wybitnych polskich artystów jazzowych (np. Krzysztof Komeda)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 wokalistki wykonujące klasyczny soul lub neo-soul", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 artystów brytyjskiej inwazji (oprócz The Beatles)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 amerykańskich i szwedzkich superproducentów muzyki pop (np. Max Martin)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 słynne studia nagraniowe na świecie (np. Abbey Road)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 artystów, którzy zdobyli status EGOT (Emmy, Grammy, Oscar, Tony)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 raperów, którzy zginęli tragicznie u szczytu swojej kariery", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 polskie festiwale muzyki alternatywnej lub jazzowej", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 awangardowych artystów muzycznych (np. Björk)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 polskie ludowe instrumenty muzyczne", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 wielkie międzynarodowe wytwórnie płytowe (tzw. Major labels)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 polskie zespoły grające punk rocka", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 artystów muzyki funk lub disco z lat 70.", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 zespoły tworzące w nurcie post-punk lub new wave", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 piosenki z gatunku grunge", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 piosenki nagrane w duecie przez wielkie divy muzyki pop", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 wybitnych polskich autorów tekstów piosenek (tekściarzy)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 włoskie określenia tempa w muzyce klasycznej (np. allegro)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 słynnych basistów", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 polskich kompozytorów muzyki współczesnej (np. Penderecki)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 raperów, którzy zdobyli Oscara za najlepszą piosenkę oryginalną", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 albumy hip-hopowe nagrodzone statuetką Grammy w kategorii Album Roku (lub Rap Album of the Year)", cat: "music", difficulty: "hard" },
  { q: "Podaj 3 marki samochodów", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki telefonów", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki laptopów", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki butów sportowych", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki odzieży sportowej", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki czekolady", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki lodów", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki wody mineralnej", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 sieci restauracji fast food", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 sieci supermarketów w Polsce", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 popularne gry wideo", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 przeglądarki internetowe", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 serwisy społecznościowe", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 elementy komputera", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 polskie portale internetowe", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki telewizorów", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 popularne aplikacje na telefon", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 polskie sieci sklepów odzieżowych", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki napojów gazowanych", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 polskie marki kosmetyczne", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki samochodów z Niemiec", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 firmy produkujące zabawki", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki chipsów i przekąsek", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 sieci kin w Polsce", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki stacji benzynowych", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 komunikatory internetowe", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 platformy ze sklepami dla graczy", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 polskie portale aukcyjne i sprzedażowe", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki past do zębów", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki klocków dla dzieci", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 sieci drogerii w Polsce", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 gigantów technologicznych z USA (Big Tech)", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 programy biurowe (np. z pakietu Office)", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 polskie sieci aptek", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki szamponów do włosów", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 urządzenia podłączane do komputera przez USB", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki kawy ziarnistej lub rozpuszczalnej", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 banki", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki aparatów fotograficznych", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 systemy operacyjne na komputery lub telefony", cat: "brands", difficulty: "easy" },
  { q: "Podaj 3 marki słuchawek", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki konsol do gier", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 platformy streamingowe", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki motocykli", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki rowerów", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki luksusowych samochodów", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki zegarków", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki kosmetyków", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki perfum", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki energetyków", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki sprzętu AGD", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki mebli", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 linie lotnicze", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 programy antywirusowe", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 firmy produkujące procesory lub karty graficzne", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki opon samochodowych", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 polskie marki odzieżowe (z segmentu premium lub casual)", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki sprzętu audio i hi-fi", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 sieci sklepów z elektroniką w Polsce", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki samochodów z Japonii", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 aplikacje do nawigacji GPS", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki samochodów dostawczych i ciężarowych", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 platformy z krótkimi filmikami (shortami)", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 polskie firmy produkujące gry wideo (studia deweloperskie)", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 aplikacje do zamawiania jedzenia lub przejazdów", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 rodzaje portów/złączy w komputerze", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki odkurzaczy", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki karmy dla zwierząt domowych", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 urządzenia wchodzące w skład inteligentnego domu (smart home)", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 firmy świadczące usługi telekomunikacyjne w Polsce", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 formaty plików graficznych lub tekstowych", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 firmy kurierskie działające w Polsce", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki gitar lub innych instrumentów muzycznych", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 aplikacje do edycji zdjęć lub wideo na telefon", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki elektrycznych hulajnóg na wynajem", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 serwisy chmurowe do przechowywania plików (np. Dysk Google)", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 firmy produkujące cywilne drony", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 marki monitorów komputerowych", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 polskie platformy VOD (wideo na życzenie)", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 darmowe usługi cyfrowe oferowane przez Google", cat: "brands", difficulty: "medium" },
  { q: "Podaj 3 języki programowania", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 marki smartwatchy", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 marki drukarek", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 frameworki lub biblioteki programistyczne", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 silniki, na których tworzy się gry (game engines)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 luksusowe domy mody (High Fashion)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 marki produkujące mikrofony i sprzęt studyjny", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 firmy z prywatnego sektora kosmicznego (np. SpaceX)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 kryptowaluty", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 systemy zarządzania bazami danych (np. MySQL)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 duże polskie firmy z branży IT (software house / korporacje)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 dystrybucje systemu Linux", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 marki ciągników rolniczych", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 programy komputerowe do tworzenia grafiki 3D", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 firmy projektujące układy scalone (poza Intelem i AMD, np. ARM)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 marki luksusowych jachtów lub motorówek", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 protokoły sieciowe (np. HTTP, FTP)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 marki profesjonalnego sprzętu medycznego (np. rezonanse, USG)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 polskie startupy technologiczne, które odniosły globalny sukces", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 usługi w chmurze dla biznesu (np. Amazon Web Services)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 systemy ERP (do zarządzania przedsiębiorstwem)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 marki luksusowych zegarków szwajcarskich", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 firmy produkujące samoloty pasażerskie lub wojskowe", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 edytory kodu lub środowiska programistyczne IDE", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 marki produkujące zaawansowany sprzęt sieciowy (routery, switche)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 popularne modele lub narzędzia wykorzystujące sztuczną inteligencję (AI)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 polskie marki kosmetyków naturalnych", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 języki znaczników lub arkuszy stylów (np. HTML)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 marki tzw. supersamochodów lub hipersamochodów", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 metodyki lub ramy zarządzania projektami IT (np. Scrum)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 popularne usługi typu VPN", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 historyczne marki telefonów komórkowych, które zniknęły z czołówki rynku", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 marki produkujące profesjonalny sprzęt dla DJ-ów", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 platformy SaaS do tworzenia e-sklepów (e-commerce)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 polskie marki zegarków (współczesne lub historyczne)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 typy matryc stosowanych w nowoczesnych monitorach/TV (np. OLED, IPS)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 firmy zajmujące się produkcją oprogramowania z zakresu cyberbezpieczeństwa", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 programy używane przez architektów i inżynierów (tzw. oprogramowanie CAD)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 marki tzw. perfum niszowych", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 firmy specjalizujące się w zaawansowanej robotyce (np. Boston Dynamics)", cat: "brands", difficulty: "hard" },
  { q: "Podaj 3 polskich królów", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 języki europejskie", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 polskie święta", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 polskie festiwale", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 rzeczy związane z Bożym Narodzeniem", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 rzeczy związane z Wielkanocą", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 rzeczy związane z Halloween", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 postacie z polskich legend", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 polskie symbole narodowe", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 tradycyjne polskie imiona męskie", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 tradycyjne polskie imiona żeńskie", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 elementy stroju rycerza", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 bronie używane w średniowieczu", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 historyczne środki transportu (np. dyliżans)", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 znane postacie z mitologii greckiej", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 rzeczy kojarzące się ze starożytnym Egiptem", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 rzeczy kojarzące się z kulturą Japonii", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 rzeczy kojarzące się z Dzikim Zachodem", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 rodzaje sztuki (np. malarstwo, rzeźbiarstwo)", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 zawody artystyczne lub związane z teatrem", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 typy przedstawień teatralnych (np. komedia, dramat)", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 przedmioty, które można zobaczyć w muzeum", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 elementy znajdujące się na zamku (np. fosa, wieża)", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 znane zabytki w Paryżu", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 znane zabytki w Rzymie", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 znane zabytki w Londynie", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 polskie miasta o bardzo długiej historii", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 dawne zawody rzemieślnicze (np. kowal, bednarz)", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 polskie pieśni patriotyczne lub historyczne", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 polskie stroje ludowe (np. krakowski)", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 znanych piratów z historii lub popkultury", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 polskie przysłowia", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 tradycyjne polskie ozdoby choinkowe", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 znane na świecie karnawały lub święta ludowe", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 rzeczy związane z obchodami Walentynek", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 słynnych królów lub królowe (niekoniecznie z Polski)", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 epoki historyczne (np. starożytność, średniowiecze)", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 słynne księżniczki z bajek lub legend", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 polskie tradycje lub obrzędy weselne", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 instrumenty wykorzystywane w muzyce ludowej", cat: "history", difficulty: "easy" },
  { q: "Podaj 3 starożytne cywilizacje", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 greckich bogów olimpijskich", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 mitologiczne stworzenia", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 bitwy z historii Polski", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 polskich prezydentów", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 słynnych odkrywców", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 polskich malarzy", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 polskich pisarzy", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 polskie powieści", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 bajki braci Grimm", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 polskie legendy", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 polskie tańce ludowe", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 polskie kabarety", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 słynne rzeźby świata", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 dzieła Leonarda da Vinci", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 dzieła Szekspira", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 słynne muzea świata", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 słynne budowle Polski", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 zabytki UNESCO na świecie", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 rzymskich bogów", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 bogów egipskich", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 postacie z mitologii nordyckiej", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 dynastie rządzące w Polsce", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 polskich dowódców wojskowych z historii", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 wynalazki epoki starożytności", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 słynne bitwy starożytności lub średniowiecza (na świecie)", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 zagranicznych malarzy epoki renesansu lub baroku", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 amerykańskich prezydentów z historii", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 państwa, które wzięły udział w I wojnie światowej", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 gatunki literackie", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 epoki w literaturze lub sztuce (np. renesans, romantyzm)", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 słynne obrazy świata (np. Mona Lisa)", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 symbole lub elementy herbu Warszawy, Krakowa i Gdańska", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 zabytki Krakowa", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 zabytki Warszawy", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 główne religie świata", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 słynne światowe teatry lub opery (budynki)", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 polskie potrawy regionalne (jako element dziedzictwa kulturowego)", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 mniejszości etniczne lub grupy górali zamieszkujące Polskę", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 słynne polskie aktorki lub aktorów teatralnych", cat: "history", difficulty: "medium" },
  { q: "Podaj 3 wynalazki XIX wieku", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 rzeczy które wynaleziono w XX wieku", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 polskich kompozytorów klasycznych", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 polskich poetów romantycznych", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 słynnych malarzy impresjonistycznych", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 słynnych architektów", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 filozofów starożytnych", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 słynnych naukowców", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 polskich noblistów", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 starożytne cuda świata", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 polskich królów z dynastii Jagiellonów", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 cesarzy rzymskich", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 faraonów starożytnego Egiptu", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 wielkie rewolucje z historii świata (np. francuska)", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 polskich malarzy nurtu historycznego (np. Jan Matejko)", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 bogów słowiańskich", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 słynne traktaty, pokoje lub unie (np. Unia Lubelska)", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 kluczowe bitwy z okresu II wojny światowej", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 wielkie odkrycia geograficzne (np. morska droga do Indii)", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 dzieła polskiej literatury epoki renesansu lub baroku", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 wielkich filozofów epoki oświecenia", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 słynnych rzeźbiarzy epoki renesansu", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 dynastie rządzące w historii Anglii lub Francji", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 prądy w sztuce współczesnej (np. kubizm, surrealizm)", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 polskich pisarzy lub poetów dwudziestolecia międzywojennego", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 ważne wydarzenia polityczne z historii Polski w XX wieku", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 dowódców Armii Krajowej lub bohaterów Polskiego Państwa Podziemnego", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 słynne kobiety-władczynie z historii świata", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 słynnych wynalazców epoki rewolucji przemysłowej (XVIII/XIX w.)", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 style architektoniczne (np. gotyk, klasycyzm)", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 elementy klasycznej architektury greckiej lub rzymskiej (np. kolumna dorycka)", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 plemiona słowiańskie zamieszkujące w średniowieczu dzisiejsze ziemie polskie", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 polskie zrywy lub powstania narodowe", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 słynnych wodzów lub strategów z czasów starożytnych", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 historyczne polskie zjazdy, sejmy lub konfederacje", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 miejsca w Polsce wpisane na Listę Światowego Dziedzictwa UNESCO", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 ważne postacie z czasów rewolucji francuskiej", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 nurty filozoficzne (np. stoicyzm, nihilizm)", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 polskich twórców kultury tworzących na emigracji (np. Gombrowicz)", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 dawne waluty, którymi posługiwano się w Europie przed wprowadzeniem Euro", cat: "history", difficulty: "hard" },
  { q: "Podaj 3 gry karciane", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 gry planszowe", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 przedmioty szkolne", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy w plecaku szkolnym", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy które znajdziesz na plaży", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy na weselu", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy na siłowni", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy w aptece", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy które mają koła", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy które można recyklingować", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 elementy garderoby zimowej", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 formy transportu publicznego", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 polskie imiona żeńskie", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 polskie imiona męskie", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy, które znajdziesz w kuchni", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 meble, które są w salonie", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 przedmioty używane do higieny osobistej", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 narzędzia ogrodowe", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 zabawki na placu zabaw", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 ubrania na lato", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rodzaje obuwia", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 nakrycia głowy", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 przybory do sprzątania", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy przydatne podczas deszczu", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 przedmioty noszone w portfelu lub torebce", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 zewnętrzne części ludzkiego ciała", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy, które są w kolorze czerwonym", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 zawody, w których nosi się mundur", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 ludzkie zmysły", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy, które można kupić w piekarni", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 miejsca idealne na spacer w Polsce", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 popularne polskie imiona dla psów", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy potrzebne do malowania obrazu", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 miesiące letnie lub wiosenne", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rzeczy, które zabierasz ze sobą w podróż", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 maszyny latające", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 owady, które potrafią użądlić", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 smaki soków owocowych", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 przedmioty zrobione ze szkła", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 części, z których składa się rower", cat: "misc", difficulty: "easy" },
  { q: "Podaj 3 rodzaje tańca towarzyskiego", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 znaki zodiaku", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 rzeczy niezbędne na camping", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 zawody medyczne", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 zawody w cyrku", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 zawody w budownictwie", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 zawody artystyczne", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 zawody prawnicze", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 kamienie szlachetne", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 metale szlachetne", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 narzędzia stolarskie", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 rodzaje energii odnawialnej", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 rodzaje diet", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 zawody wykonywane głównie w biurze", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 instrumenty pomiarowe (np. linijka)", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 materiały lub tkaniny (np. bawełna)", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 popularne fobie ludzkie", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 zjawiska pogodowe", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 polskie tradycje studniówkowe", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 rodzaje butów damskich (np. szpilki)", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 naturalne surowce", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 typy statków morskich", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 formy transportu wodnego (np. prom, barka)", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 zawody związane z lotnictwem", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 rodzaje ubezpieczeń", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 ciężkie maszyny budowlane", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 rzeczy z apteczki pierwszej pomocy", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 elementy wyposażenia strażaka", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 gry liczbowe lub loterie w Polsce", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 style tańca nowoczesnego", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 przedmioty produkowane z recyklingowanego papieru", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 znane polskie organizacje charytatywne (np. WOŚP)", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 narządy wewnętrzne człowieka", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 kości w ciele człowieka", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 przyrządy optyczne (np. lupa)", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 rodzaje mostów (np. zwodzony)", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 typy budynków mieszkalnych (np. bliźniak)", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 rzeczy, które można wygrać na festynie", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 popularne w Polsce zawody rzemieślnicze", cat: "misc", difficulty: "medium" },
  { q: "Podaj 3 zawody przyszłości", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 popularne teorie spiskowe", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 języki posługujące się innym alfabetem niż łaciński", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 rodzaje chmur", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 fazy Księżyca", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 pierwiastki chemiczne (poza wodorem, tlenem i węglem)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 jednostki miar, które nie należą do układu SI (np. cal)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 wynalazki przypisywane Nikoli Tesli", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 gazy szlachetne", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 polskie ordery lub odznaczenia państwowe", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 główne części mikroskopu", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 działy matematyki", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 rodzaje promieniowania elektromagnetycznego", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 dziedziny lub nurty w psychologii", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 rdzenne polskie rasy psów", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 podstawowe pojęcia makroekonomiczne (np. inflacja)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 typy wiązań chemicznych (np. kowalencyjne)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 dawne, staropolskie jednostki miar (np. łokieć)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 władców widniejących na polskich banknotach obiegowych", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 pierwiastki promieniotwórcze", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 państwa w Europie korzystające z cyrylicy", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 organizacje międzynarodowe (poza ONZ, UE i NATO)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 słynne polskie wynalazki lub rozwiązania techniczne (np. wycieraczki samochodowe)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 nazwy gwiazdozbiorów (poza znakami zodiaku)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 dialekty lub gwary występujące na terytorium Polski", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 subkultury młodzieżowe z ubiegłego wieku (np. punk)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 części anatomiczne ludzkiego mózgu", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 etapy podziału komórki (mitozy)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 formy krasowe (np. stalaktyt)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 wielkości fizyczne wektorowe (np. siła)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 polskie słowa zawierające przynajmniej 3 znaki diakrytyczne (np. żółć)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 alternatywne metody parzenia kawy (np. drip, chemex)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 rodzaje ożaglowania lub żagli na statku", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 minerały z dziesięciostopniowej skali twardości Mohsa", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 przyrządy nawigacyjne używane dawniej lub dziś", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 systemy liczbowe (np. system binarny)", cat: "misc", difficulty: "hard" },
  { q: "Podaj 3 polskie słowa uznawane obecnie za archaizmy (np. białogłowa)", cat: "misc", difficulty: "hard" },
];

// Return questions for a difficulty, optionally limited to a set of categories.
// `cats` may be an array/Set of category keys; empty or omitted means all.
export function poolFor(difficulty, cats) {
  const catSet = cats && cats.length ? new Set(cats) : null;
  return QUESTIONS.filter((x) => {
    if (difficulty && difficulty !== 'all' && x.difficulty !== difficulty) return false;
    if (catSet && !catSet.has(x.cat)) return false;
    return true;
  });
}

export function countFor(difficulty, cats) {
  return poolFor(difficulty, cats).length;
}
